use crate::commands::{
    apply_config_patch, fix_issues, get_system_status, get_status_light, list_history, list_recipes,
    list_model_profiles, upsert_model_profile, delete_model_profile,
    get_cached_model_catalog, refresh_model_catalog, resolve_provider_auth,
    check_openclaw_update, extract_model_profiles_from_config,
    list_agents_overview, create_agent, delete_agent, setup_agent_identity, list_session_files,
    clear_all_sessions, analyze_sessions, delete_sessions_by_ids, preview_session,
    preview_rollback, rollback, run_doctor_command,
    resolve_api_keys, read_raw_config, open_url, chat_via_openclaw,
    backup_before_upgrade, list_backups, restore_from_backup, delete_backup,
    list_channels_minimal,
    list_discord_guild_channels,
    refresh_discord_guild_channels,
    restart_gateway,
    set_global_model,
    set_agent_model,
    list_bindings,
    assign_channel_agent,
    list_ssh_hosts, upsert_ssh_host, delete_ssh_host,
    ssh_connect, ssh_disconnect, ssh_status,
    ssh_exec, sftp_read_file, sftp_write_file, sftp_list_dir, sftp_remove_file,
    remote_read_raw_config, remote_get_system_status,
    remote_list_agents_overview, remote_list_channels_minimal, remote_list_bindings,
    remote_restart_gateway, remote_apply_config_patch,
    remote_create_agent, remote_delete_agent, remote_setup_agent_identity,
    remote_assign_channel_agent, remote_set_global_model, remote_set_agent_model,
    remote_run_doctor, remote_fix_issues, remote_list_history, remote_preview_rollback, remote_rollback,
    remote_list_discord_guild_channels, remote_write_raw_config,
    remote_analyze_sessions, remote_delete_sessions_by_ids,
    remote_list_session_files, remote_clear_all_sessions, remote_preview_session,
    remote_list_model_profiles, remote_upsert_model_profile, remote_delete_model_profile, remote_resolve_api_keys,
    remote_extract_model_profiles_from_config, remote_refresh_model_catalog,
    remote_chat_via_openclaw, remote_check_openclaw_update,
    run_openclaw_upgrade, remote_run_openclaw_upgrade,
    remote_backup_before_upgrade, remote_list_backups, remote_restore_from_backup, remote_delete_backup,
    list_cron_jobs, get_cron_runs, trigger_cron_job, delete_cron_job,
    remote_list_cron_jobs, remote_get_cron_runs, remote_trigger_cron_job, remote_delete_cron_job,
    get_watchdog_status, deploy_watchdog, start_watchdog, stop_watchdog, uninstall_watchdog,
    remote_get_watchdog_status, remote_deploy_watchdog, remote_start_watchdog, remote_stop_watchdog, remote_uninstall_watchdog,
    read_app_log, read_error_log, remote_read_app_log, remote_read_error_log,
};
use crate::cli_runner::{
    queue_command, remove_queued_command, list_queued_commands,
    discard_queued_commands, queued_commands_count,
    preview_queued_commands, apply_queued_commands, CommandQueue,
    remote_queue_command, remote_remove_queued_command, remote_list_queued_commands,
    remote_discard_queued_commands, remote_queued_commands_count,
    remote_preview_queued_commands, remote_apply_queued_commands, RemoteCommandQueues,
    CliCache,
};
use crate::ssh::SshConnectionPool;

pub mod cli_runner;
pub mod commands;
pub mod config_io;
pub mod doctor;
pub mod history;
pub mod logging;
pub mod models;
pub mod recipe;
pub mod ssh;

pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .manage(SshConnectionPool::new())
        .manage(CommandQueue::new())
        .manage(RemoteCommandQueues::new())
        .manage(CliCache::new())
        .invoke_handler(tauri::generate_handler![
            get_system_status,
            get_status_light,
            list_recipes,
            list_model_profiles,
            get_cached_model_catalog,
            refresh_model_catalog,
            upsert_model_profile,
            delete_model_profile,
            resolve_provider_auth,
            list_agents_overview,
            create_agent,
            delete_agent,
            setup_agent_identity,
            list_session_files,
            clear_all_sessions,
            analyze_sessions,
            delete_sessions_by_ids,
            preview_session,
            check_openclaw_update,
            extract_model_profiles_from_config,
            apply_config_patch,
            list_history,
            preview_rollback,
            rollback,
            run_doctor_command,
            fix_issues,
            resolve_api_keys,
            read_raw_config,
            open_url,
            chat_via_openclaw,
            backup_before_upgrade,
            list_backups,
            restore_from_backup,
            delete_backup,
            list_channels_minimal,
            list_discord_guild_channels,
            refresh_discord_guild_channels,
            restart_gateway,
            set_global_model,
            set_agent_model,
            list_bindings,
            assign_channel_agent,
            list_ssh_hosts,
            upsert_ssh_host,
            delete_ssh_host,
            ssh_connect,
            ssh_disconnect,
            ssh_status,
            ssh_exec,
            sftp_read_file,
            sftp_write_file,
            sftp_list_dir,
            sftp_remove_file,
            remote_read_raw_config,
            remote_get_system_status,
            remote_list_agents_overview,
            remote_list_channels_minimal,
            remote_list_bindings,
            remote_restart_gateway,
            remote_apply_config_patch,
            remote_create_agent,
            remote_delete_agent,
            remote_setup_agent_identity,
            remote_assign_channel_agent,
            remote_set_global_model,
            remote_set_agent_model,
            remote_run_doctor,
            remote_fix_issues,
            remote_list_history,
            remote_preview_rollback,
            remote_rollback,
            remote_list_discord_guild_channels,
            remote_write_raw_config,
            remote_analyze_sessions,
            remote_delete_sessions_by_ids,
            remote_list_session_files,
            remote_clear_all_sessions,
            remote_preview_session,
            remote_list_model_profiles,
            remote_upsert_model_profile,
            remote_delete_model_profile,
            remote_resolve_api_keys,
            remote_extract_model_profiles_from_config,
            remote_refresh_model_catalog,
            remote_chat_via_openclaw,
            remote_check_openclaw_update,
            run_openclaw_upgrade,
            remote_run_openclaw_upgrade,
            remote_backup_before_upgrade,
            remote_list_backups,
            remote_restore_from_backup,
            remote_delete_backup,
            list_cron_jobs,
            get_cron_runs,
            trigger_cron_job,
            delete_cron_job,
            remote_list_cron_jobs,
            remote_get_cron_runs,
            remote_trigger_cron_job,
            remote_delete_cron_job,
            get_watchdog_status,
            deploy_watchdog,
            start_watchdog,
            stop_watchdog,
            uninstall_watchdog,
            remote_get_watchdog_status,
            remote_deploy_watchdog,
            remote_start_watchdog,
            remote_stop_watchdog,
            remote_uninstall_watchdog,
            read_app_log,
            read_error_log,
            remote_read_app_log,
            remote_read_error_log,
            queue_command,
            remove_queued_command,
            list_queued_commands,
            discard_queued_commands,
            queued_commands_count,
            preview_queued_commands,
            apply_queued_commands,
            remote_queue_command,
            remote_remove_queued_command,
            remote_list_queued_commands,
            remote_discard_queued_commands,
            remote_queued_commands_count,
            remote_preview_queued_commands,
            remote_apply_queued_commands,
        ])
        .run(tauri::generate_context!())
        .expect("failed to run app");
}
